#
#
#
#


SOURCE_DIR = src
OBJECT_DIR = objects
BIN_DIR    = bin

default :
	cd $(OBJECT_DIR); make

clean : 
	rm -f $(OBJECT_DIR)/* \
		$(BIN_DIR)/*.exe \
		$(BIN_DIR)/*.ppm \
		$(BIN_DIR)/*.tab \
		$(BIN_DIR)/*.bin
                   
