      ! conserve quantatiy
      real*8 den(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8  px(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8  py(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8  pz(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8 den2(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8  px2(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8  py2(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8  pz2(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8 den3(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8 px3(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8 py3(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8 pz3(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8 ene(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8 ene2(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8 ene3(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8  bx(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8  by(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8  bz(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8  bx2(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8  by2(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8  bz2(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8  bx3(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8  by3(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8  bz3(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
