      real*8 vxt(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8 vyt(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8 vzt(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8 vxt2(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &           ,kbeg-kbuf:kend+kbuf)
      real*8 vyt2(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &           ,kbeg-kbuf:kend+kbuf)
      real*8 vzt2(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &           ,kbeg-kbuf:kend+kbuf)
      real*8 Ex(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8 Ey(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8 Ez(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
      real*8 btemp(ibeg-ibuf:iend+ibuf,jbeg-jbuf:jend+jbuf
     &          ,kbeg-kbuf:kend+kbuf)
